### ISSUE TITLE
CDR Register OpenID Configuration does not specify token signing algorithm support 

### ISSUE THREAD

**Issue by CDR-Register-Stream** [ConsumerDataStandardsAustralia/register#169]
The CDR Register currently specifies **PS256** as the signing algorithm used.

The OpenID Configuration Document published currently specifies this value using the field `request_object_signing_alg_values_supported`. 

However, this is incorrect and instead the field `token_endpoint_auth_signing_alg_values_supported` should be used.

**Comment by CDR-Register-Stream** [comment]
This issue will track updates to the Swagger definition.

**Comment by CDR-API-Stream** [comment]
This issue will be addressed in the CDS standards maintenance process. [Issue 440](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/440) has been raised to track this work through the process

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes) as part of Standards Maintenance [issue 440](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/440). 

Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/212) for further details.
