### ISSUE TITLE
RegisterDataHolderAuth schema in GetDataHolderBrands descriptions to be clarified

### ISSUE THREAD

**Issue by CDR-Register-Stream** [ConsumerDataStandardsAustralia/register#189]
Currently the description in the RegisterDataHolderAuth schema states the following:

> **RegisterDataHolderAuth**
> 
> _Provides details of authorisation endpoints for Data Holders_
> 
> Name | Type | Required | Restrictions | Description
> -- | -- | -- | -- | --
> registerUType | string | true | none | The type of authentication and authorisation mechanism in use
> jwksEndpoint | string | true | none | JWKS endpoint for private_key_jwt client authentication with Data Recipient
> 
> Property | Value
> -- | --
> registerUType | SIGNED-JWT

Description of this schema and field names should elaborate on this configuration being used for DH to ADR client authentication

**Comment by CDR-Register-Stream** [comment]
We are proposing that the descriptions will be updated as follows

**RegisterDataHolderAuth**
**Old Description:** ~~Provides details of authorisation endpoints for Data Holders~~
**New Description:**  Defines the mechanism used and associated endpoints for Data Holder to Data Recipient authentication 

**registerUType:** Unchanged

**jwksEndpoint**
**Old Description:** ~~JWKS endpoint for private_key_jwt client authentication with Data Recipient~~
**New Description:** JWKS endpoint used for authentication by the Data Holder with the Data Recipient

**Comment by CDR-API-Stream** [comment]
This issue will be addressed in the CDS standards maintenance process. [Issue 441](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/441) has been raised to track this work through the process

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes) as part of Standards Maintenance [issue 441](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/441). 

Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/212) for further details.
